name: Push image tag 9 / stretch to docker hub

on:
  push:
    branches: [ "main" ]
    paths:
      - 'dockerfile.debian09'
      - '.github/workflows/docker-image-09.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dockerfile.debian09'
      - '.github/workflows/docker-image-09.yml'

env:
  PLATAFORM_ARCH: linux/386,linux/amd64,linux/arm/v7
  CONTAINER_REPO: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}
  
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATAFORM_ARCH }}
                
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile.debian09
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
            ${{ env.CONTAINER_REPO }}:9
            ${{ env.CONTAINER_REPO }}:stretch
