name: Push image tag 10-slim / buster-slim to docker hub

on:
  push:
    branches: [ "main" ]
    paths:
      - 'dockerfile.debian10-slim'
      - '.github/workflows/docker-image-10-slim.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dockerfile.debian10-slim'
      - '.github/workflows/docker-image-10-slim.yml'

env:
  PLATAFORM_ARCH: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
  CONTAINER_REPO: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}
  
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATAFORM_ARCH }}
                
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile.debian10-slim
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: |
            ${{ env.CONTAINER_REPO }}:10-slim
            ${{ env.CONTAINER_REPO }}:buster-slim
